
-- Hive script to change the payt_cmpn table format to parquet-snappy

-- jar file need to be present in the directory from where the hive script is executed
USE cba;

DROP TABLE IF EXISTS cba.payt_cmpn_temp_text;
CREATE TABLE cba.payt_cmpn_temp_text
(
RECORD_TYPE             		STRING COMMENT 'Record Type',                  
BLANK_FIELD             		STRING COMMENT 'Blank field',                  
SPECIAL_CHAR            		STRING COMMENT 'Special Character',                  
PAYMENT_COMPONENT_ID    		STRING COMMENT 'Artificial Primary Key. Set from Payment Journal',                  
EVENT_CREATION_DATE     		STRING COMMENT 'Date on which the parent .payment event. for this component was created. Set from Payment Journal',                  
PAYMENT_EVENT_ID        		STRING COMMENT 'Foreign key referencing the parent payment event. Set from Payment Journal',                  
CREDIT_DEBIT_FLAG       		STRING COMMENT 'Flag column specifying whether this is a [C]redit or [D]ebit component.Set from Payments. Set from Payments',                  
COMPONENT_ID            		STRING COMMENT 'Used by the source systems as a unique identifier for the component within the context of the payment. Set from Channel',                  
COMPONENT_TYPE_CAT_ID   		STRING COMMENT 'Foreign key referencing the component type. Set from Payments',                  
PRODUCT_TYPE     				STRING COMMENT 'Product system that holds the account being credited. Set from Payments',                  
PROCESSING_SYSTEM_CAT_ID 		STRING COMMENT 'Foreign Key referencing the target system for this transaction. Set from Payments',                  
REFERENCE_TRANSACTION_CODE  	STRING COMMENT 'Group reference transaction code. Set from Channel/Payments',                  
INPUT_TRANSACTION_CODE			STRING  COMMENT 'Source system transaction code. Set from Channel',                  
INPUT_TRANS_CODE_FMT_CAT_ID   	STRING COMMENT 'Foreign key referencing the format the input transaction code is supplied in. Set from Channel',                  
INPUT_TRANSACTION_SUBCODE       STRING COMMENT 'Source system transaction subcode. Set from Channel',                  
PRODUCT_SYSTEM_TRANS_CODE       STRING COMMENT 'Transaction code used by target product system. Format as per required format of the target product system. Not supplied for CASH, ChequeSummary and Cheque components. Set from Payments',                  
PRODUCT_SYSTEM_TRANS_SUBCODE    STRING COMMENT 'Sub-code for legacy transaction codes. Set from Payments',       
TRANSACTION_AMOUNT              STRING COMMENT 'Monetary value of the component. Set from Channel',                  
CHEQUE_AMOUNT                   STRING COMMENT 'Monetary value of the cheques that make up the transaction amount. Set from Channel',                  
NUM_CHEQUES             		INT    COMMENT 'Number of cheques for a cheque component. Input by user. Set from Channel',                   
SERIAL_NUMBER                   STRING COMMENT 'Cheque serial number. Set from Channel',                  
ACCOUNT_NUMBER              	STRING COMMENT 'Account number including  6-digit ledger BSB. Not supplied for CASH, ChequeSummary and Cheque components. Set from Channel',                  
ACC_NUMBER_FORMAT_CAT_ID   		STRING COMMENT 'Foreign key referencing the format of the supplied account number. Not supplied for CASH, ChequeSummary and Cheque components. Set from Channel',                  
INPUT_DESCRIPTION               STRING COMMENT 'Description of the component as entered by the client. Set from Channel',                  
RESPONSIBILITY_CENTRE           INT   COMMENT 'RCN of GL account if account type is GL. Set from Channel',                   
CLEARING_DATE                 	STRING COMMENT 'The date the funds will be available for debit. Set from Payments',                  
POSTING_DATE                  	STRING COMMENT 'The date the transaction was posted. Set from Payments',                  
VALUE_DATE                  	STRING COMMENT 'The date the funds will start accruing interest and fees. Set from Payments',                  
ACCOUNT_TITLE                   STRING COMMENT 'Used only by recordPayment in some instances . processing types "DE IN", "DE In Return", "Open Payment" , "DE Dishonour" and when not a CBA account. Set from Channel',                  
CUSTOMER_REF_NUMBER           	STRING COMMENT 'Used only by recordPayment when payment BPAY. Set from Channel',                  
BILLER_REF_NUMBER           	STRING COMMENT 'Biller code. Used only when payment is BPAY. Set from Channel',                  
OVERRIDE_FLAG                  	STRING COMMENT 'Flag to indicate whether this component was overridden. Default = N. Set from Payments',                  
OVERRIDE_USER_TYPE          	STRING COMMENT 'The type of user who performed the override (T)eller or (S)upervisor. Mandatory if the transaction is overridden. Set from Payments',                  
OVERRIDE_USER_ID            	STRING COMMENT 'PeopleSoft Id of the user who authorised the override. Mandatory if the transaction is overridden. Set from Channel',                  
TARGET_SYS_REF_NUMBER     		STRING COMMENT 'Key required by target system to reverse the posting. Composed of event Receipt_Number + Component_id. Set from Payments',                  
REVERSAL_FLAG                  	STRING COMMENT 'Flag to indicate whether this component is a reversal. Default = .N.. Set from Payments',                  
REV_EVENT_RECEIPT_NUMBER     	STRING COMMENT 'Receipt number of original component if this is a reversal. Set from Payments',                  
REVERSED_COMPONENT_ID           STRING COMMENT 'Component Id of original component if this is a reversal. Set from Payments',                  
COMPONENT_PROC_STATUS_CAT_ID   	STRING COMMENT 'Foreign key referencing the processing status for the component record. Set from Payments',                  
INTENTED_ACCOUNT_NUMBER         STRING COMMENT 'Account Number the transaction was intended for when a failure occurred. Account_Number if Component_Proc_status_cat_id  = S else blank. Set from Payments',                  
INTN_ACCT_NUMB_FRMT_CATG_I      STRING COMMENT 'Foreign key referencing the format of the supplied account number. Set from Payments',                  
INTENTED_PROC_SYS_CAT_ID    	STRING COMMENT 'Foreign key referencing the system this payment would have been directed if it had not encountered an error. Set from Payments',                  
IFW_ERROR_CODE              	STRING COMMENT 'The IFW error code for the error that caused the payments to be redirected to suspense. Mandatory if component processing status not = Processed.. Set from Payments',                  
AGENT_NUMBER               		STRING COMMENT 'Agency owed account. Set from Channel',                  
APCA_IDENTIFIER                 STRING COMMENT 'Used to identify institution for Direct Entry',                  
ACCOUNT_ACCESS_CARD          	STRING COMMENT 'Used to identify institution for Direct Entry. Set from Channel',                  
REMITTER                   		STRING COMMENT 'Remitter name. Set from Channel',                  
DRN                     		STRING COMMENT 'Document Reference Number(references the related image record at FISERV). Set from Channel',  
BANK_CHQ_RECIPEINT_NAME  		STRING COMMENT 'Receipt of the bank cheque. Set from Channel',                  
PROCESSING_BSB 					STRING COMMENT 'Processing branch',      
TARGET_SYS_MULTI_REF_NUMBER  	STRING COMMENT 'Secondary key required by target system for reversals. Populated only for SAP multi-part transaction (mixed deposits. Set from Payments',                  
HOST_ERROR_DETAILS          	STRING COMMENT 'Details/Reasons of when a record is rejected by Host. Set from Payments',                  
INTENDED_TRANSACTION_CODE       STRING COMMENT 'ntended Input Transaction code when host reject occurs. Set from Payments',                  
INTENDED_SUB_TRANSACTION_CODE   STRING COMMENT 'Intended Input Sub Transaction code when host reject occurs. Set from Payments',                  
INTENDED_POSTING_DATE           STRING COMMENT 'Intended Posting Date when host reject occurs. Set from Payments',                  
INTENDED_VALUE_DATE             STRING COMMENT 'Intended Value Date when host reject occurs. Set from Payments',                  
INTENDED_CLEARING_DATE          STRING COMMENT 'Intended Clearing Date when host reject occurs ',                  
TRACE_ACCOUNT               	STRING COMMENT 'Trace account is particularly used in case of Direct Entry outbound to indicate the OFI entry the fund returned account in case of  failure (so will be the CBA accounts). For Direct Entry Inbound, trace account will be the OFI account for the internal CBA account entry.',                  
INTENDED_TRANS_CODE_FMT_CAT_ID  STRING COMMENT 'Intended trans code format cat ID',                  
CURRENCY_AMOUNT                 STRING COMMENT 'The amount of the transaction in the settlement',                  
CURRENCY_CODE                  	STRING COMMENT 'The currency used for settlement of the component',                  
CLEARING_REFERENCE_NUMBER       STRING COMMENT 'Unique ID number for the purposes of reconciling transactions in the SAP Host Reject Account. Also originating system reference number',                  
CASH_AMOUNT                 	STRING COMMENT 'ATM-DC fees charged, Fee charged by the ATM Operator in AUD Currency. RTGS Commission Zero filled if no fee is charged',                  
FEE_TOTAL_GROSS_AMOUNT        	STRING COMMENT 'ATM-DC fees charged, Fee charged by the ATM Operator in AUD Currency. RTGS Commission Zero filled if no fee is charged.',                  
FEE_TOTAL_NET_AMOUNT          	STRING COMMENT 'CBA transaction transaction processing fee. In AUD Currency. RTGS Cable Charge Zero filled if no fee is charged.Transaction exchange rate',                  
EXCHANGE_RATE                  	STRING COMMENT 'Transaction exchange rate',                  
REVERSAL_TYPE_CAT_ID       		STRING COMMENT 'Reversal Type.',                  
BENEFICIARY_BANK_ID             STRING COMMENT 'Beneficiary Bank Id',                  
BENEFICIARY_BANK_NAME           STRING COMMENT 'Beneficiary Bank Name',                  
REM_ADDR_FMT_TYPE_CAT_ID        STRING COMMENT 'Remitter Address Format Type',                  
REM_ADDR_LINE1            		STRING COMMENT 'Remitter Address Line 1',                  
REM_ADDR_LINE2           		STRING COMMENT 'Remitter Address Line 2',                  
REM_ADDR_LINE3           		STRING COMMENT 'Remitter Address Line 3',                  
BEN_ADDR_FMT_TYPE_CAT_ID     	STRING COMMENT 'Beneficiary Address Format Type',                  
BEN_ADDR_LINE1           		STRING COMMENT 'Beneficiary Bank Address Line 1',                  
BEN_ADDR_LINE2            		STRING COMMENT 'Beneficiary Bank Address Line 2',                  
BEN_ADDR_LINE3          		STRING COMMENT 'Beneficiary Bank Address Line 3',                  
BEN_BANK_ADDR_FMT_TYPE_CAT_ID   STRING COMMENT 'Beneficiary Bank Address Format Type',                  
BEN_BANK_ADDRESS_LINE1       	STRING COMMENT 'Beneficiary Bank Address Line 1',                  
BEN_BANK_ADDRESS_LINE2       	STRING COMMENT 'Beneficiary Bank Address Line 2',                  
BEN_BANK_ADDRESS_LINE3          STRING COMMENT 'Beneficiary Bank Address Line 3',                  
SEG_GROUP_TYPE_CAT_ID         	STRING COMMENT 'Segmentation Group Type',                  
SEGMENTATION_GROUP              STRING COMMENT 'Segmentation Group',                  
SEGMENTATION_SUB_GROUP          STRING COMMENT 'Segmentation Sub Group',                  
TRACE_ORIGIONAL_DATE            STRING COMMENT 'race original date is used in case of DE type 2/3 returns to indicate the original day of the initial transaction',                  
TRACE_ORIGIONAL_APCA_ID       	STRING COMMENT 'Trace APCA/User id of the initial transaction when there is a DE type2/3 return',                  
CHEQUE_IMAGE_CAPTURE_DATE       STRING COMMENT 'Date on which the cheque image was captured',                  
BLANK_FIELD_2           		STRING COMMENT 'blank field 2'
)
COMMENT ' This table is Payment Component. Data to this table is loaded on a daily basis. It is partitioined based \
on the date from EVENT_CREATION_DATE with the partition column name as PARTITION_EVENT_CREATION_DATE. \
Table Use Parquet as the underlying file format with Snappy compression. \
Table is bucketed on PAYMENT_EVENT_ID to help sampling. And records are sorted based on EVENT_CREATION_DATE within every bucket. '
PARTITIONED BY (PARTITION_EVENT_CREATION_DATE STRING) 
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|';

